(function(current, factory){
  if(typeof module === "object" && typeof module.exports === "object"){
    module.exports = factory;
  } else {
    define([],function(){
      return factory;
    })
  }
})(this, {
  'Array' : "toolkit/commonLib/js/lib/Array",
  'echartGalleryJs': "toolkit/echarts-gl/echarts-gl.min",
  'numberPrecision' : 'toolkit/number-precision',
  'laydate' : 'toolkit/laydate/laydate',
  'svgcharts': 'toolkit/svgcharts/svgcharts',
  'd3': 'node_modules/d3/dist/d3',
  'spectrum': 'node_modules/spectrum-colorpicker/spectrum',
  'jquery': 'node_modules/jquery/dist/jquery.min',
  'bootstrap': 'node_modules/bootstrap/dist/js/bootstrap.min',
  'moment': 'node_modules/moment/min/moment.min',
  'locales': 'node_modules/moment/min/locales.min',
  'bootstrap-dialog': 'node_modules/bootstrap3-dialog/dist/js/bootstrap-dialog.min',
  'ng-dialog': 'node_modules/ng-dialog/js/ngDialog.min',
  'bootstrap-switch': 'node_modules/bootstrap-switch/dist/js/bootstrap-switch.min',
  'bootstrap-daterangepicker': 'node_modules/bootstrap-daterangepicker/daterangepicker',
  'bootstrap-datetimepicker': 'node_modules/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min',
  'bootstrap-multiselect': 'node_modules/bootstrap-multiselect/dist/js/bootstrap-multiselect',
  'jquery-ui': 'node_modules/jquery-ui/jquery-ui',
  'datatables.net': 'node_modules/datatables.net/js/jquery.dataTables',
  'datatables.net-bs': 'node_modules/datatables.net-bs/js/dataTables.bootstrap',
  'datatables.net-buttons': 'node_modules/datatables.net-buttons/js/dataTables.buttons',
  'datatables.net-buttons-bs': 'node_modules/datatables.net-buttons-bs/js/buttons.bootstrap',
  'datatables.buttons.html5': 'node_modules/datatables.net-buttons/js/buttons.html5',
  'pdfmake': 'node_modules/pdfmake/build/pdfmake.min',
  'vfs': 'node_modules/pdfmake/build/vfs_fonts',
  'datatables.buttons.flash': 'node_modules/datatables.net-buttons/js/buttons.flash',
  'datatables.net-select': 'node_modules/datatables.net-select/js/dataTables.select.min',
  'clipboard':'node_modules/clipboard/dist/clipboard.min',
  'cronGen':'toolkit/cronGen',
  'ckplayer' : 'toolkit/ckplayer/ckplayer',
  'ezuikit' : 'toolkit/ezuikit',
  'jwplayer.html5':'toolkit/jwplayer.html5',
  'jszip': 'node_modules/jszip/dist/jszip',
  'iCheck': 'node_modules/iCheck/icheck.min',
  'fastclick': 'node_modules/fastclick/lib/fastclick',
  'keyboardJS': 'node_modules/keyboardjs/dist/keyboard',
  'slimscroll': 'node_modules/jquery-slimscroll/jquery.slimscroll.min',
  'fullcalendar': 'node_modules/fullcalendar/dist/fullcalendar.min',
  'echarts': 'node_modules/echarts/dist/echarts.min',
  'bmap': 'node_modules/echarts/dist/extension/bmap.min',
  'dataTool': 'node_modules/echarts/dist/extension/dataTool',
  'macarons': 'node_modules/echarts/theme/macarons',
  'dark': 'node_modules/echarts/theme/dark',
  'slick': 'node_modules/slick-carousel/slick/slick.min',
  'ckeditor': 'node_modules/ckeditor/ckeditor',
  'ckeditor-sample': "node_modules/ckeditor/samples/js/sample",
  'angular': 'node_modules/angular/angular.min',
  'angular-route': 'node_modules/angular-route/angular-route.min',
  'angular-resource': 'node_modules/angular-resource/angular-resource.min',
  'angular-animate': 'node_modules/angular-animate/angular-animate.min',
  'angular-style':'toolkit/angular-custom/angular-style',
  'angular-dialogue':'toolkit/angular-custom/angular-dialogue',
  'angular-popup':'toolkit/angular-custom/angular-popup',
  'angular-growl': 'node_modules/angular-growl-v2/build/angular-growl.min',
  'angular-file-upload': 'node_modules/angular-file-upload/dist/angular-file-upload.min',
  'domReady': 'node_modules/requirejs-domready/domReady',
  'qrcode': 'node_modules/jquery-qrcode/jquery.qrcode.min',
  'multiselect': 'node_modules/multiselect/js/jquery.multi-select',
  'underscore': 'node_modules/underscore/underscore-min',
  'select2': 'node_modules/select2/dist/js/select2.min',
  'xlsx': 'node_modules/js-xlsx/dist/xlsx.min',
  'index-app': 'toolkit/admin-lte/app',
  'Array': 'toolkit/commonLib/js/lib/Array',
  'tools': 'toolkit/tools',
  'configs': 'toolkit/configs',
  'lodash': 'node_modules/lodash/index',
  'backbone': 'node_modules/backbone/backbone-min',
  'rappid-joint': 'toolkit/rappid/dist/rappid',
  'ztree': 'node_modules/ztree/js/jquery.ztree.core-3.5',
  'ztree-excheck': 'node_modules/ztree/js/jquery.ztree.excheck-3.5',
  'sparkline': 'toolkit/sparkline/dist/jquery.sparkline.min',
  'baiduMap': 'https://api.map.baidu.com/getscript?v=2.0&ak=eMekSXxqG1j2wLM57RFN61l8T6eB1EDx&services=',
  'BMapLib' : 'toolkit/component/BMapLib',
  'simulate' : 'toolkit/component/simulate',
  'simulate_time' : 'toolkit/component/simulate_time',
  'commonMethod' : 'toolkit/component/commonMethod',
  'dropdowntree' : 'toolkit/component/dropdowntree',
  'clock' : 'toolkit/component/explainer/clock'
})